### ISSUE TITLE
vago might be broken after recent changes in varnish

### ISSUE THREAD

**Issue by fgsch** [phenomenes/vago#11]
As per https://github.com/varnishcache/varnish-cache/issues/2377, recent changes to varnish might have broken vago and any software using it (e.g. varnishstatbeat).

**Comment by phenomenes** [comment]
Since vago is using `type` and `ident` from `fantom`, this change doesn't have any effect.
Thanks for the heads up.

**Comment by fgsch** [comment]
👍
